# Generated by Django 4.2 on 2023-06-23 14:32

from django.db import migrations
from externals.keycloak import get_access_token
from externals.bimdata_api import api_request
from externals.bimdata_api import ApiClient
from webhooks.utils import register_webhook
import os


def create_link_with_platform_front(apps, schema_editor):
    access_token = get_access_token()
    platform_front_client_id = os.environ.get("PLATFORM_FRONT_CLIENT_ID")
    api_request(
        "post",
        "/private/platform-link",
        access_token,
        raise_for_status=True,
        json={"client_id": platform_front_client_id},
    )


def add_webhook_to_cloud_platform(apps, schema_editor):
    access_token = get_access_token()
    client = ApiClient(access_token)

    clouds = client.collaboration_api.get_clouds()

    for cloud in clouds:
        register_webhook(
            cloud_id=cloud["id"],
            events=[
                "bcf.topic.creation",
                "visa.validation.add",
                "visa.validation.remove",
            ],
            access_token=access_token,
        )


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        migrations.RunPython(create_link_with_platform_front),
        migrations.RunPython(add_webhook_to_cloud_platform),
    ]
