# Generated by Django 4.2 on 2023-07-21 14:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebHook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_id",
                    models.PositiveIntegerField(
                        help_text="Webhook id from API", unique=True
                    ),
                ),
                ("cloud_id", models.PositiveIntegerField()),
                ("secret", models.CharField(max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
