# Generated by Django 4.2.21 on 2025-05-28 15:18
from bimdata_api_client.exceptions import NotFoundException
from django.db import migrations

from externals.bimdata_api import ApiClient
from externals.keycloak import get_access_token


def check_platform_url_defined(apps, schema_editor):
    Webhook = apps.get_model("webhooks", "Webhook")
    access_token = get_access_token()
    client = ApiClient(access_token)
    for webhook in Webhook.objects.all():
        try:
            client.webhook_api.update_web_hook(
                cloud_pk=webhook.cloud_id,
                id=webhook.webhook_id,
                patched_web_hook_request={
                    "events": [
                        "bcf.topic.creation",
                        "bcf.topic.update",
                        "visa.validation.add",
                        "visa.validation.remove",
                    ],
                },
            )
        except NotFoundException:
            print(
                f"No Webhook found for id: {webhook.webhook_id} and cloud: {webhook.cloud_id}"
            )


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0001_initial"),
    ]

    operations = [migrations.RunPython(check_platform_url_defined)]
