repos:
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    - id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.11.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/pycqa/flake8
    rev: '6.1.0'
    hooks:
    - id: flake8
      args: ["--config=setup.cfg"]
-   repo: local
    hooks:
    - id: migrations-check
      language: system
      name: Check for uncreated migrations.
      entry: bash -c "./manage.py makemigrations --check --dry-run"
      types: ["python"]
      pass_filenames: false
