# Generated by Django 4.2.20 on 2025-04-25 12:35
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("api_id", models.PositiveIntegerField(unique=True)),
                ("cloud_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file_creation", models.BooleanField(default=False)),
                ("file_deletion", models.BooleanField(default=False)),
                ("folder_creation", models.BooleanField(default=False)),
                ("folder_deletion", models.BooleanField(default=False)),
                ("visa_creation", models.BooleanField(default=False)),
                ("visa_deletion", models.BooleanField(default=False)),
                ("visa_validation", models.BooleanField(default=False)),
                ("visa_denied", models.BooleanField(default=False)),
                ("bcf_topic_creation", models.BooleanField(default=False)),
                ("bcf_topic_deletion", models.BooleanField(default=False)),
                ("invitation_accepted", models.BooleanField(default=False)),
                ("model_creation", models.BooleanField(default=False)),
                ("model_deletion", models.BooleanField(default=False)),
                (
                    "periodic_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="notification.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("consumed", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notification.project"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "webhook_id",
                    models.PositiveIntegerField(help_text="Webhook id from API", unique=True),
                ),
                ("secret", models.CharField(max_length=256)),
                ("event", models.CharField(max_length=256)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notification.project"
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "event")},
            },
        ),
    ]
