# Generated by Django 4.2.20 on 2025-04-18 15:12
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("api_id", models.PositiveIntegerField(unique=True)),
                ("cloud_id", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file_creation", models.BooleanField(default=False)),
                ("file_deletion", models.BooleanField(default=False)),
                ("file_new_version", models.BooleanField(default=False)),
                ("folder_creation", models.BooleanField(default=False)),
                ("folder_deletion", models.BooleanField(default=False)),
                ("visa_creation", models.BooleanField(default=False)),
                ("visa_deletion", models.BooleanField(default=False)),
                ("visa_validation", models.BooleanField(default=False)),
                ("visa_denied", models.BooleanField(default=False)),
                ("bcf_topic_creation", models.BooleanField(default=False)),
                ("bcf_topic_deletion", models.BooleanField(default=False)),
                ("invitation_accepted", models.BooleanField(default=False)),
                ("meta_building_creation", models.BooleanField(default=False)),
                ("meta_building_deletion", models.BooleanField(default=False)),
                ("model_deletion", models.BooleanField(default=False)),
                (
                    "periodic_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notification.project"
                    ),
                ),
            ],
        ),
    ]
