# Generated by Django 5.2 on 2025-06-11 13:34
import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="recipients_group_id",
        ),
        migrations.AddField(
            model_name="subscription",
            name="recipients_group_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(), default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
