# Generated by Django 5.2 on 2025-06-11 13:12
import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="recipients_group_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(), size=None
            ),
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="recipients_group_id",
            new_name="recipients_group_ids",
        ),
    ]
