# Generated by Django 4.2.20 on 2025-04-25 14:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="locale",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "English")], default="en", max_length=2
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="referer",
            field=models.URLField(
                blank=True, default="http://localhost:80800", max_length=255, null=True
            ),
        ),
    ]
