# Generated by Django 5.2.4 on 2025-09-24 11:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_remove_subscription_recipients_group_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="locale",
            field=models.CharField(
                choices=[("fr", "Français"), ("en", "English"), ("de", "Deutsch")],
                default="en",
                max_length=2,
            ),
        ),
    ]
