# Generated by Django 2.0.7 on 2018-07-25 14:25

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=255, unique=True, verbose_name='Subject identifier')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Access Token')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Refresh Token')),
                ('userinfo', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Subject extra data')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paltform_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OpenID Connect user',
                'verbose_name_plural': 'OpenID Connect users',
            },
        ),
    ]
