# Generated by Django 2.0.7 on 2018-07-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='id_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
