version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_PASSWORD: "platform_back"
          POSTGRES_DB: "platform_back"
          POSTGRES_USER: "platform_back"
    working_directory: ~/repo

jobs:
  test:
    <<: *container_config
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            - v1-dependencies

      - run:
          name: install dependencies
          command: pipenv sync --dev

      # run tests!
      - run:
          name: run tests
          command: pipenv run python manage.py test

      - save_cache:
          paths:
            - ~/.local
            - ~/.cache
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

  deploy:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: push to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t bimdata/platform_back:latest .
            docker push bimdata/platform_back:latest

            # deploy master branch
            docker pull bimdata/deployment:latest
            docker run -e ANSIBLE_VAULT_PASSWD -it bimdata/deployment:latest ansible-playbook -i inventories/staging deploy.yml --tags=platform_back --extra-vars "ansible_ssh_private_key_file=./files/deploy_rsa" --user=deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
