version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/python:3.7
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_PASSWORD: "platform_back"
          POSTGRES_DB: "platform_back"
          POSTGRES_USER: "platform_back"
    working_directory: ~/repo

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - repo-{{ .Branch }}-{{ .Revision }}

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  test:
    <<: *container_config
    steps:
      - *restore_repo

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            - v1-dependencies

      - run:
          name: install dependencies
          command: pipenv sync --dev

      # run tests!
      - run:
          name: run tests
          command: pipenv run python manage.py test

      - save_cache:
          paths:
            - ~/.local
            - ~/.cache
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

  deploy:
    <<: *container_config
    steps:
      - *restore_repo
      - setup_remote_docker
      - run:
          name: push to docker hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t bimdata/platform_back:latest .
            docker push bimdata/platform_back:latest

            # deploy master branch
            docker pull bimdata/deployment:latest
            docker run -it bimdata/deployment:latest ansible-playbook -i inventories/staging deploy.yml --tags=platform_back --extra-vars "ansible_ssh_private_key_file=./files/deploy_rsa" --user=deploy

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - deploy:
          requires:
            - checkout_code
            - test
          filters:
            branches:
              only:
                - master
