# Generated by Django 2.1.1 on 2018-10-03 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='IfcMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifc_id', models.PositiveIntegerField()),
                ('last_sent', models.CharField(choices=[('S', 'success'), ('E', 'failed')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ifcmail',
            unique_together={('user', 'ifc_id')},
        ),
    ]
