# Generated by Django 3.1.13 on 2022-04-14 14:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_guidedtour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidedtour",
            name="name",
            field=models.CharField(
                choices=[
                    ("PLATFORM_INTRO", "PLATFORM_INTRO"),
                    ("PLATFORM_VISA", "PLATFORM_VISA"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="guidedtour",
            unique_together={("user", "name")},
        ),
    ]
