# Generated by Django 4.2 on 2023-04-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_auto_20220414_1425"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
