# Generated by Django 4.2 on 2023-08-04 12:16
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
