# Generated by Django 4.2 on 2023-06-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="action",
            new_name="event",
        ),
        migrations.AddField(
            model_name="notification",
            name="event_type",
            field=models.CharField(default="bcf", max_length=255),
            preserve_default=False,
        ),
    ]
