# Generated by Django 4.2 on 2023-10-04 09:41
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_user_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteCloud",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cloud_id", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="favoriteproject",
            constraint=models.UniqueConstraint(
                fields=("user", "project_id"), name="unique project_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="favoritecloud",
            constraint=models.UniqueConstraint(
                fields=("user", "cloud_id"), name="unique cloud_id"
            ),
        ),
    ]
