# Generated by Django 4.2.3 on 2023-12-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_favoriteproject_favoritecloud_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="user_user_email_5f6a77_idx"),
        ),
    ]
