# Generated by Django 4.2.17 on 2025-03-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_alter_user_options_user_user_user_email_5f6a77_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="initial_referer",
            field=models.URLField(
                blank=True, default="http://localhost:8080", max_length=255, null=True
            ),
        ),
    ]
