# Generated by Django 4.2.17 on 2025-04-03 12:21
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.db import migrations
from django.db import models


def check_platform_url_defined(apps, schema_editor):
    if not settings.PLATFORM_URL:
        raise ImproperlyConfigured(
            "Env variable PLATFORM_URL must be defined during migrations"
        )


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0016_user_initial_referer"),
    ]

    operations = [
        migrations.RunPython(check_platform_url_defined),
        migrations.AlterField(
            model_name="user",
            name="initial_referer",
            field=models.URLField(
                blank=True, default=settings.PLATFORM_URL, max_length=255, null=True
            ),
        ),
    ]
