# Generated by Django 5.2.4 on 2025-08-20 14:24
import json
from django.db import migrations


def add_user_notification_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")

    schedule = CrontabSchedule.objects.create(
        minute="*",
        hour="*",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
    )

    PeriodicTask.objects.create(
        crontab=schedule,
        name="Send user notifications",
        task="user.tasks.notifications.send_user_notifications",
        description="Group & send notifications to all users (visa, bcf)",
        kwargs=json.dumps(
            {
                "notification_delay_minutes": 5,
            }
        ),
    )


def reverse(apps, schema_editor):
    # No reverse needed
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_alter_user_initial_referer"),
    ]

    operations = [migrations.RunPython(add_user_notification_task, reverse)]
