
name: main

on: push

env:
  app: platform_back

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: psycopg2 prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install python3.9-dev libpq-dev -y
      - name: Install poetry
        uses: snok/install-poetry@v1.3.0
      - name: Install library
        run: poetry install --no-interaction
      - name: Run tests
        run: poetry run pytest
        env: 
          TEST_DB_HOST: postgres
          TEST_DB_PORT: 5432
          TEST_DB_NAME: ${{ github.run_id }}
          TEST_DB_USER: bimdata
          TEST_DB_PASSWORD: bimdata

  build-and-push:
    runs-on: self-hosted
    needs: test
    if: contains('
          refs/heads/develop
          refs/heads/release
          refs/heads/master
          refs/heads/main'
        , github.ref)
    steps:
      - uses: actions/checkout@v2
      - name: Login to BIMData Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker-registry.bimdata.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - id: tag
        name: Get docker tag
        uses: bimdata/actions/get-docker-tag@v1
        with:
          branch: ${{ github.ref }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          pull: true
          tags: |
            docker-registry.bimdata.io/bimdata/${{ env.app }}:${{ github.sha }}
            docker-registry.bimdata.io/bimdata/${{ env.app }}:${{ steps.tag.outputs.tag }}
  
  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Login to BIMData Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker-registry.bimdata.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - id: tag
        name: Get docker tag
        uses: bimdata/actions/get-docker-tag@v1
        with:
          branch: ${{ github.ref }}
      - name: Deploy on ${{ steps.tag.outputs.tag }}
        uses: bimdata/actions/deployment@v1
        with:
          inventory: ${{ steps.tag.outputs.tag }}
          app: ${{ env.app }}
          vault-pass: ${{ secrets.ANSIBLE_VAULT_PASSWD }}


